# -*- coding: utf-8 -*-
"""Emit site/verified.js — which brown claims the modern dictionary confirms.

Brown used to mean one thing: a curated table holds a key for this word. That
is a statement about our tables, not about Truku, and it counted a value like
`nxa` — which still had an x in it, a letter modern Truku does not have — as
verified. This splits brown in two.

A modern value is VERIFIED when that exact string is one of the 40,760 types in
attested_modern.json: every plain [a-z'] type of the modern Truku dictionary and
the spoken-word list, PLUS every token of the 26,663 modern corpus sentences.
The sentences matter -- the particle `o` is in 6,361 of them and in no headword
list, so a headword-only snapshot called 517 occurrences of it unverified. It is
UNVERIFIED when a curated table proposed it but no modern source has the word:
often a perfectly regular derivation of an attested root, sometimes an
invention. The reader is entitled to know which one is on screen.

A multi-word value is verified only if every word in it is.

Run from tools/orthography/ after build_modern_map.py.
"""
import io, json, os, re

H = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
H = os.path.normpath(H)
SITE = os.path.join(H, "site")
PAIR = re.compile(r'"((?:[^"\\]|\\.)*)"\s*:\s*"((?:[^"\\]|\\.)*)"')


def read(p):
    return io.open(p, encoding="utf-8").read()


def table(app, name):
    i = app.index("var %s = {" % name)
    return dict(PAIR.findall(app[i:app.index("\n  };", i)]))


def main():
    lex = set(json.load(io.open(os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "attested_modern.json"),
        encoding="utf-8")))
    app = read(os.path.join(SITE, "app.js"))
    ov, cl = table(app, "WORD_OVERRIDES"), table(app, "CLITIC_FORMS")
    m = read(os.path.join(SITE, "modern_map.js"))
    a = m.index("window.MODERN_MAP = {") + len("window.MODERN_MAP = ")
    mp = json.loads(m[a:m.index("\n};", a) + 2])

    # Every value a brown span can display. CLITIC_FORMS hands the word back
    # unchanged, so there the key IS the value.
    vals = set(ov.values()) | set(mp.values()) | set(cl)

    def ok(v):
        parts = v.split()
        return bool(parts) and all(p in lex for p in parts)

    good = sorted(v for v in vals if ok(v))
    bad = len(vals) - len(good)

    out = io.open(os.path.join(SITE, "verified.js"), "w",
                  encoding="utf-8", newline="\n")
    out.write(
        "// Generated by tools/orthography/build_verified.py — do not edit by hand.\n"
        "// The modern spellings that a modern source actually has: %d of the %d\n"
        "// distinct values the curated tables can put on screen. A value NOT in\n"
        "// here is still a proposal — app.js paints it in the pale brown.\n"
        "window.MODERN_VERIFIED = {\n" % (len(good), len(vals)))
    for v in good:
        out.write('  "%s": 1,\n' % v)
    out.write("};\n")
    out.close()
    print("verified values: %d   unverified: %d   (of %d distinct)"
          % (len(good), bad, len(vals)))
    print("wrote site/verified.js")


if __name__ == "__main__":
    main()
