# -*- coding: utf-8 -*-
"""Emit site/verified.js — which brown claims the modern dictionary confirms.

Brown used to mean one thing: a curated table holds a key for this word. That
is a statement about our tables, not about Truku, and it counted a value like
`nxa` — which still had an x in it, a letter modern Truku does not have — as
verified. This splits brown in two.

A modern value is VERIFIED two ways, and the file records which.

  1  LISTED. The exact string is one of the 40,760 types in
     attested_modern.json: every plain [a-z'] type of the modern Truku
     dictionary and the spoken-word list, PLUS every token of the 26,663 modern
     corpus sentences. The sentences matter -- the particle `o` is in 6,361 of
     them and in no headword list, so a headword-only snapshot called 517
     occurrences of it unverified.

  2  A REGULAR INFLECTION of a listed root, per inflection.py: AF, PF, LF, the
     referential s-, the causative p-, the preterite -n-, the imperatives, and
     the stacks those build, with the root's modern gloss required to agree
     with his own Chinese for the word. The wordlist records the forms someone
     happened to write down, not every form of every word -- `qriban` is absent
     while its own siblings `qribun` 剪成 and `qribi` 要剪下 are there. That is a
     listing gap, and painting it as unverified told the reader the wrong
     thing.

Everything else is UNVERIFIED: a curated table proposed the word and no modern
source has it, nor is it a paradigm slot of anything that does. The reader is
entitled to know which of the three is on screen; app.js paints 1 and 2 alike
in the deep brown and leaves the rest pale.

A multi-word value is verified only if every word in it is, and at the weaker
of the two levels.

Run from tools/orthography/ after build_modern_map.py.
"""
import io, json, os, re
from inflection import Inflection

H = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
H = os.path.normpath(H)
SITE = os.path.join(H, "site")
PAIR = re.compile(r'"((?:[^"\\]|\\.)*)"\s*:\s*"((?:[^"\\]|\\.)*)"')


def read(p):
    return io.open(p, encoding="utf-8").read()


def table(app, name):
    i = app.index("var %s = {" % name)
    return dict(PAIR.findall(app[i:app.index("\n  };", i)]))


def main():
    lex = set(json.load(io.open(os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "attested_modern.json"),
        encoding="utf-8")))
    app = read(os.path.join(SITE, "app.js"))
    ov, cl = table(app, "WORD_OVERRIDES"), table(app, "CLITIC_FORMS")
    m = read(os.path.join(SITE, "modern_map.js"))
    a = m.index("window.MODERN_MAP = {") + len("window.MODERN_MAP = ")
    mp = json.loads(m[a:m.index("\n};", a) + 2])

    # Every value a brown span can display. CLITIC_FORMS hands the word back
    # unchanged, so there the key IS the value.
    vals = set(ov.values()) | set(mp.values()) | set(cl)

    inf = Inflection(lex, mp)

    def level(v):
        """2 = every word listed, 1 = every word listed or regularly inflected,
        0 = no."""
        parts = v.split()
        if not parts:
            return 0
        if all(p in lex for p in parts):
            return 2
        if all(p in lex or inf.regular(p) for p in parts):
            return 1
        return 0

    # app.js's attested() splits a value on its spaces and asks about each word
    # separately, so a multi-word value has to put its own words in here too or
    # it can never be verified. One value has a space in it (`empaa su`, a
    # proclitic join), and `empaa` was reaching the page pale for want of a key.
    keys = set(vals)
    for v in vals:
        keys |= set(v.split())

    lv = {v: level(v) for v in keys}
    listed = sorted(v for v in keys if lv[v] == 2)
    infl = sorted(v for v in keys if lv[v] == 1)
    good = sorted(listed + infl)

    out = io.open(os.path.join(SITE, "verified.js"), "w",
                  encoding="utf-8", newline="\n")
    out.write(
        "// Generated by tools/orthography/build_verified.py — do not edit by hand.\n"
        "// The modern spellings a modern source vouches for: %d of the %d distinct\n"
        "// values the curated tables can put on screen. 1 = a modern source lists\n"
        "// this exact word (%d). 2 = the wordlist does not list it, but it is a\n"
        "// regular inflection of a root the wordlist does list, and that root means\n"
        "// what he says the word means (%d) — a listing gap, not a lexical one.\n"
        "// app.js paints both in the deep brown; a value NOT in here is still a\n"
        "// proposal and stays pale.\n"
        "window.MODERN_VERIFIED = {\n"
        % (len(good), len(keys), len(listed), len(infl)))
    for v in good:
        out.write('  "%s": %d,\n' % (v, 1 if lv[v] == 2 else 2))
    out.write("};\n")
    out.close()
    print("listed: %d   regularly inflected: %d   unverified: %d   (of %d distinct)"
          % (len(listed), len(infl), len(keys) - len(good), len(keys)))
    print("wrote site/verified.js")


if __name__ == "__main__":
    main()
